USE [szkoleniaBHP]
GO

/****** Object:  Table [dbo].[RODZAJ_SZKOLENIA]    Script Date: 8/20/2364 2:56:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RODZAJ_SZKOLENIA](
	[RSKEY] [int] IDENTITY(1,1) NOT NULL,
	[NAZWA] [varchar](250) NULL,
	[G_TEORETYCZNYCH] [int] NULL,
	[G_PRAKTYCZNYCH] [int] NULL,
	[TYTU?2] [varchar](250) NULL,
	[TYTU?3] [varchar](250) NULL,
	[DRUK_NAZWA] [varchar](250) NULL,
	[FORMA_KURSU] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[RSKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


